/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'UpdateTask': ApiRouteHandler<{ title?: string; description?: string; status?: 'pending' | 'in-progress' | 'completed' }, ApiResponse<200, { id: string; title: string; description: string; status: 'pending' | 'in-progress' | 'completed'; createdAt: string; updatedAt: string }> | ApiResponse<404, { error: string }>, never>
    'GetTasks': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, Array<{ id: string; title: string; description: string; status: 'pending' | 'in-progress' | 'completed'; createdAt: string; updatedAt: string }>>, never>
    'GetTaskById': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { id: string; title: string; description: string; status: 'pending' | 'in-progress' | 'completed'; createdAt: string; updatedAt: string }> | ApiResponse<404, { error: string }>, never>
    'DeleteTask': ApiRouteHandler<Record<string, unknown>, ApiResponse<404, { error: string }>, never>
    'CreateTask': ApiRouteHandler<{ title: string; description: string; status: 'pending' | 'in-progress' | 'completed' }, ApiResponse<201, { id: string; title: string; description: string; status: 'pending' | 'in-progress' | 'completed'; createdAt: string; updatedAt: string }>, never>
  }
    
}