/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'SetupUserAccount': EventHandler<{ userId: string; name: string; email: string }, never>
    'SendWelcomeEmail': EventHandler<{ userId: string; name: string; email: string }, { topic: 'email.sent'; data: { userId: string; email: string; type: string; sentAt: string } }>
    'RegisterUser': ApiRouteHandler<{ name: string; email: string; password: string }, ApiResponse<201, { userId: string; name: string; email: string; status: string; createdAt: string }>, { topic: 'user.registered'; data: { userId: string; name: string; email: string } }>
    'LogNotification': EventHandler<{ userId: string; email: string; type: string; sentAt: string }, never>
    'GetUserStatus': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { userId: string; name: string; email: string; status: string; createdAt: string; emailSent: boolean; accountSetup: boolean }> | ApiResponse<404, { error: string }>, never>
    'ProcessGreeting': EventHandler<{ timestamp: string; appName: string; greetingPrefix: string; requestId: string }, never>
    'HelloAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; status: string; appName: string }>, { topic: 'process-greeting'; data: { timestamp: string; appName: string; greetingPrefix: string; requestId: string } }>
  }
    
}