/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'SynthesisAgent': EventHandler<{ researchId: string; query: string; findings: Array<unknown>; analysis: unknown }, { topic: 'report.completed'; data: { researchId: string; query: string; report: unknown } }>
    'ResearchStatusAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { researchId: string; query: string; status: string; progress: { planning: string; research: string; analysis: string; synthesis: string }; report?: unknown; createdAt: string; completedAt?: string }> | ApiResponse<404, { error: string }>, never>
    'ResearchAPI': ApiRouteHandler<{ query: string; depth: 'quick' | 'standard' | 'deep' }, ApiResponse<202, { researchId: string; query: string; depth: string; status: string; message: string }>, { topic: 'research.started'; data: { researchId: string; query: string; depth: string } }>
    'ResearchAgent': EventHandler<{ researchId: string; query: string; depth: string; plan: { research_topics: Array<string>; key_questions: Array<string>; approach: string; estimated_time?: number } }, { topic: 'research.completed'; data: { researchId: string; query: string; plan: unknown; findings: Array<unknown> } }>
    'ReportLogger': EventHandler<{ researchId: string; query: string; report: unknown }, never>
    'PlanningAgent': EventHandler<{ researchId: string; query: string; depth: string }, { topic: 'plan.completed'; data: { researchId: string; query: string; depth: string; plan: { research_topics: Array<string>; key_questions: Array<string>; approach: string; estimated_time?: number } } }>
    'AnalysisAgent': EventHandler<{ researchId: string; query: string; plan: unknown; findings: Array<unknown> }, { topic: 'analysis.completed'; data: { researchId: string; query: string; findings: Array<unknown>; analysis: unknown } }>
    'ProcessGreeting': EventHandler<{ timestamp: string; appName: string; greetingPrefix: string; requestId: string }, never>
    'HelloAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; status: string; appName: string }>, { topic: 'process-greeting'; data: { timestamp: string; appName: string; greetingPrefix: string; requestId: string } }>
  }
    
}